scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: employees
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/q/metrics'
    scrape_interval: 1s
  - job_name: skills
    static_configs:
     - targets: [ 'host.docker.internal:8083' ]
    metrics_path: '/q/metrics'
    scrape_interval: 1s