version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger2
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5775:5775/udp"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "4317:4317"
    restart: always